[tool.poetry]
name = "h3-java-python-client"
version = "0.1.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
aioquic = "^1.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"